### ISSUE TITLE
Missing methods from CMP

### ISSUE THREAD

**Issue by slhsxcmy** [s-group-dev/react-usercentrics#21]
https://docs.usercentrics.com/#/cmp-v2-ui-api has some methods that this package doesn't include yet, such as
- areAllConsentsAccepted
- acceptAllConsents

Is it possible to add them? I'm happy to do a Pull Request.

**Comment by iiroj** [comment]
Thanks for the issue! We haven't implemented these methods yet because so far all our requirements have always targeted specific consents.

What is the use-case for checking if all consents are accepted?

In any case, feel free to open a PR by following the conventions:

1. create methods to `src/utils.ts`:
    - `areAllConsentsAccepted = () => boolean`
    - `acceptsAllConsents = () => Promise<void>`
1. add hooks for methods to `src/hooks/`:
    - `useAreAllConsentsAccepted = () => boolean | null`
        - we should return `null` when Usercentrics has not loaded, same as with `useHasServiceConsent()`
    - not sure if we need `useCcceptsAllConsents`, but I guess it would return a callback `() => Promise<void>`
1. add tests
2. update `README.md` with examples

**Comment by slhsxcmy** [comment]
We want to maintain backward compatibility for when consent was all or nothing. And I was just curious : )

For now I think `areAllConsentsAccepted` and `useAreAllConsentsAccepted` are sufficient, I'll open PR. Thanks!

**Comment by iiroj** [comment]
I'll consider this solved after merging #22, thanks for the PR!

**Comment by slhsxcmy** [comment]
Thank you!

**Comment by teopkuz** [comment]
Hey, can you export this hook useAreAllConsentsAccepted in the index.d.ts file like: 

`export { useAreAllConsentsAccepted } from './hooks/use-are-all-consents-accepted.js';`
